In [10]:
from scipy import stats
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas_datareader import DataReader
from datetime import datetime
plt.style.use('fivethirtyeight')
import operator

In [8]:
ticker = 'ADBE'
start = datetime(2019,1,1)
end = datetime(2021,4,1)
df = DataReader(ticker,  'yahoo', start, end)

In [9]:
df

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2019-01-02,226.169998,219.000000,219.910004,224.570007,2784100,224.570007
2019-01-03,223.630005,215.149994,220.880005,215.699997,3663500,215.699997
2019-01-04,227.649994,217.479996,219.839996,226.190002,4043400,226.190002
2019-01-07,232.600006,227.289993,229.949997,229.259995,3638500,229.259995
2019-01-08,233.770004,228.330002,232.649994,232.679993,3685900,232.679993
...,...,...,...,...,...,...
2021-03-26,469.769989,449.049988,450.250000,469.089996,3614400,469.089996
2021-03-29,472.000000,462.500000,469.029999,469.320007,3141900,469.320007
2021-03-30,469.089996,461.500000,462.579987,465.459991,2436300,465.459991
2021-03-31,482.410004,468.700012,469.700012,475.369995,3155900,475.369995
2021-04-01,487.040009,480.709991,483.119995,483.339996,2664000,483.339996

In [25]:
a = df.Close[1:].tolist()

In [26]:
b = df.Close[:-1].tolist()

In [35]:
c = np.subtract(a,b)

In [39]:
ret = np.true_divide(c, b)

In [40]:
ret

array([-3.94977516e-02,  4.86323859e-02,  1.35726249e-02,  1.49175532e-02,
        1.18188073e-02,  9.93930964e-03, -9.25269028e-04, -1.25868468e-02,
        3.32537651e-02, -1.69171341e-03,  1.01260466e-02,  1.27250437e-02,
       -1.47872348e-02,  5.29010971e-03, -1.05246057e-02,  9.85322977e-03,
       -1.26556068e-02, -1.48025708e-02,  1.84664197e-02,  2.12222738e-02,
       -1.77549200e-03,  2.97518007e-02,  3.14052875e-04, -1.84444395e-03,
       -2.39827244e-03,  1.28477750e-02,  5.40861731e-03,  1.15328778e-02,
       -4.36157230e-03, -3.45833817e-04, -2.65242716e-03, -6.32111995e-03,
        1.12489255e-03, -1.31730465e-03,  4.42265708e-03, -1.08149396e-03,
        1.00533839e-02,  6.43133247e-03, -1.52146788e-03,  5.75241815e-03,
       -2.21582739e-02, -3.02137732e-03, -3.80764227e-03, -3.66609674e-03,
       -2.81844986e-03,  2.44169970e-02,  9.77168299e-03,  3.30156383e-03,
        1.25198483e-02, -3.95980650e-02,  2.60614352e-03,  1.03196910e-02,
       -2.61125550e-03,  1.70940271e-02, -1.69959511e-02,  9.93487061e-03,
        1.26587389e-02, -1.22369067e-02,  4.53610756e-03,  1.12320854e-02,
        2.13142084e-02, -3.01284963e-03,  5.52769092e-04, -1.32964470e-02,
       -1.64247421e-03,  5.08500763e-03,  6.69590705e-04,  9.62859746e-03,
        1.17831703e-03, -1.47144339e-04,  1.32426943e-03, -2.90209588e-03,
       -7.29462669e-03,  4.15659702e-03,  6.06121923e-03,  2.30704198e-02,
       -1.09159328e-02,  8.02320333e-03,  1.54865221e-02,  1.48248806e-02,
        1.08687537e-02, -2.03975588e-02, -1.30933170e-02,  2.12414948e-02,
       -6.72310036e-03, -2.32320251e-02, -1.08282493e-03, -3.54077576e-03,
        9.75380673e-03, -3.87101349e-02,  1.55396823e-02,  1.82447666e-02,
        2.43117560e-02, -1.30487810e-02, -1.57226864e-02,  9.51168997e-03,
        1.34858126e-02, -2.68611423e-02,  1.89604016e-03,  1.26651786e-02,
       -1.75022286e-02,  4.13345842e-03, -1.31507622e-02, -4.38168896e-02,
        3.73701607e-02,  1.54441369e-02,  7.10988252e-03,  1.22271325e-02,
        7.83718956e-03, -1.55168943e-02,  3.07984396e-03, -1.95061607e-03,
       -7.31085452e-03,  4.81262699e-03,  4.28154082e-03,  5.21352437e-02,
        3.74300134e-02, -9.20194272e-03,  1.80405763e-03, -3.96838433e-02,
        2.60443795e-03,  1.56207043e-02,  4.84255655e-03,  2.14492023e-02,
        1.39553253e-03,  1.43003993e-02, -5.62643491e-03, -3.48706336e-03,
        4.22553388e-03,  9.13872014e-03,  2.01965957e-03,  5.91679873e-03,
       -2.13303482e-03, -9.91060196e-03,  1.20706650e-02,  2.23010405e-03,
       -1.03521401e-02,  5.47460717e-03, -2.17139179e-03,  7.76271305e-03,
       -4.96334832e-03,  8.22718212e-03, -1.30111734e-02, -1.16528434e-02,
       -1.57424222e-02, -1.40528318e-03, -1.58491186e-02, -4.54530200e-02,
        2.08660523e-02,  9.81795759e-03,  3.03093561e-02, -9.90668352e-03,
       -2.09612080e-02,  1.56591707e-02, -3.24385487e-02, -3.34912288e-03,
        1.67663715e-02,  1.80897197e-03, -7.84807361e-03,  2.03703318e-02,
       -1.31718737e-02, -1.82488093e-02,  2.23055790e-02,  2.45903580e-03,
       -2.52893661e-02,  1.59500937e-02, -7.39627771e-03, -7.24050996e-03,
        7.61194478e-03,  1.10681442e-02, -9.76541289e-03, -1.97936920e-02,
       -1.13139036e-02,  5.93895866e-03,  8.63957936e-04,  1.18702648e-03,
        1.64540559e-02,  6.22065462e-03, -1.74575896e-02,  5.50553603e-03,
       -1.19107089e-02, -1.69119936e-03, -1.79137874e-02,  1.82038075e-02,
        2.29968102e-02, -2.20922063e-02, -4.64800931e-03, -1.28145106e-02,
       -2.21846943e-02,  2.15255012e-02,  1.67400795e-02, -2.16628973e-04,
       -2.19212982e-02,  1.27017044e-02,  2.58877019e-03,  1.20372297e-02,
       -1.83265568e-03,  5.79601079e-03, -2.39450306e-02, -1.26880155e-02,
       -1.38166742e-02,  4.97140471e-03, -2.15484938e-02,  8.80964378e-04,
        3.20679804e-02,  4.74600935e-03,  1.36539635e-03,  3.68550217e-04,
        2.56400484e-02, -1.72411544e-03, -3.95730416e-04, -1.15185126e-03,
        4.24865173e-02, -6.53328699e-03,  1.17258009e-02,  5.81216255e-03,
       -7.48821208e-03,  4.99539140e-03,  6.23888426e-03,  3.37259047e-03,
        1.00838666e-02, -1.14284483e-03,  1.15762633e-02, -1.66333995e-03,
       -4.33195030e-03,  1.67336018e-03,  1.99799907e-02,  8.58226916e-03,
        3.76746894e-03,  1.52074427e-03, -2.19041734e-02,  3.83155627e-03,
       -4.60660682e-03,  1.71891507e-03,  1.05600509e-02,  2.67765006e-03,
       -9.37949676e-03, -1.41375933e-03,  7.30888685e-03,  3.91554822e-02,
        1.84311043e-02, -2.93385338e-03,  4.73903903e-03,  1.00191132e-02,
       -6.11040837e-05,  4.09031139e-03,  2.09759056e-03,  4.73242777e-03,
       -1.23793372e-03, -7.40654840e-03,  4.47707022e-03,  1.40080505e-02,
       -7.83421097e-03,  5.72615024e-03, -9.58846947e-04,  1.34376564e-02,
        7.63612374e-03, -1.87990784e-03,  1.71272398e-02, -2.89326733e-03,
       -4.90381690e-03,  7.11495429e-03,  1.26237341e-02,  7.43437333e-04,
        1.71421596e-04,  4.85634525e-03, -1.10875210e-03, -1.27216361e-02,
        2.22831108e-02, -8.37492931e-03,  1.44457331e-02, -1.56976390e-02,
        1.95363247e-02,  2.44133805e-02, -3.24481233e-03,  5.22501361e-03,
       -3.72828376e-03,  1.06804439e-02, -1.94594925e-03,  1.35669676e-02,
        1.46941618e-03,  1.28855435e-02, -2.15978954e-03,  1.16932628e-02,
       -1.12711525e-02, -1.58591392e-02, -4.16678054e-02, -2.68879320e-02,
        1.01782883e-02, -3.93351382e-02,  2.25172030e-02,  4.39267613e-02,
       -3.31408973e-02,  4.45254921e-02, -3.52343194e-02, -4.06233365e-02,
       -9.19915119e-02,  8.69550855e-02, -5.15975499e-02, -9.58982645e-02,
        1.77192982e-01, -1.47451568e-01,  9.01304020e-02, -5.51618368e-02,
        4.37867861e-02, -3.95759912e-02,  4.03940977e-02,  8.88473032e-03,
       -1.31935366e-02,  5.47873870e-02, -5.21896246e-02,  4.10686611e-02,
       -4.71196982e-04, -5.35130697e-02,  9.12984323e-03, -3.40505540e-02,
        8.69180914e-02, -3.19619342e-02,  2.67050795e-02,  4.79229323e-03,
        6.11854915e-03,  6.27475300e-02, -2.41218461e-02,  3.05218006e-02,
        4.11430725e-03,  2.23771342e-03, -4.60740386e-02,  2.36481322e-02,
       -4.15712190e-03,  2.60309840e-02,  1.27869626e-02, -4.31850439e-02,
        4.71435017e-02,  1.28017901e-02, -2.77118479e-02,  1.53268644e-02,
        2.01083321e-02,  1.79428412e-02,  1.17511031e-02,  1.99032387e-03,
        1.06391760e-02, -1.70157964e-02, -1.79129237e-02, -8.84087163e-03,
        2.78847822e-02,  7.30909805e-03,  1.14955322e-02,  3.07092754e-02,
       -3.80572801e-03,  8.08539715e-03, -2.24004689e-02, -3.87646081e-03,
        1.24209638e-02,  1.78238153e-02,  7.96685598e-03,  1.95034331e-03,
       -1.33180261e-03, -1.05663354e-02,  1.84033342e-02,  1.24204758e-02,
       -1.55863824e-03,  2.43227001e-02, -4.70723995e-02,  4.86754055e-02,
       -1.27908990e-02,  2.57388179e-02,  4.42096035e-03,  1.68565174e-02,
        1.79565677e-02,  2.48358792e-02,  4.35430668e-03, -2.01339130e-02,
        1.22081626e-02, -2.29545680e-02, -6.37121975e-03,  2.61904409e-02,
        1.03374607e-02,  7.13947993e-03,  2.17631423e-02, -7.13672642e-03,
        1.85152386e-02,  6.90439546e-03,  1.16309693e-02, -5.09009231e-02,
       -1.96397551e-02, -1.77506804e-03, -1.55192745e-02,  1.43798934e-02,
        5.28420861e-02, -2.41395007e-02,  1.73311654e-03, -2.99067474e-02,
       -3.31216174e-03,  1.57793418e-02, -1.10729725e-02,  9.34617576e-03,
        5.91340170e-03,  1.23951932e-02,  8.21478627e-03, -2.34387970e-03,
        5.79521225e-03,  3.24797563e-02, -3.13287335e-02, -1.39689007e-02,
       -1.81822225e-02,  2.32749905e-02,  1.04634539e-02, -5.37750093e-03,
        8.89182398e-03,  2.64184055e-02, -3.23617607e-03,  3.56485809e-02,
       -1.09931651e-02,  6.50857226e-03,  1.70690848e-02,  9.09522495e-02,
       -3.43809405e-02,  1.19924656e-02, -5.90579308e-03,  2.83605001e-02,
        1.10805483e-02, -4.87073822e-02, -3.12327407e-02, -6.05968155e-02,
        3.75002410e-02, -6.67413704e-03, -1.03095023e-02,  3.08899912e-02,
        2.42020326e-02, -4.35429358e-02, -3.57145422e-03, -1.42314994e-02,
        1.73030201e-02,  2.34210407e-02, -3.36702087e-02, -5.78243827e-03,
        2.58942951e-02,  1.81958627e-02,  1.67852611e-03,  2.24798425e-03,
        1.85144001e-02, -4.10802970e-02,  1.56162157e-02, -1.53966128e-02,
        2.95836623e-02, -4.68416828e-03,  2.30625202e-02,  1.73849190e-02,
        6.69416667e-03, -1.55548211e-02, -1.01913920e-02,  3.33236246e-03,
       -1.51545185e-02, -1.25207112e-03,  2.79025622e-03, -2.49213355e-02,
        1.01323280e-02, -2.72261777e-02,  7.07067606e-03, -4.51145028e-02,
        9.05964094e-03, -3.03831617e-02, -4.83114210e-03,  2.04072156e-02,
        7.31466076e-02,  1.89643290e-02, -3.70615814e-03, -4.74900229e-02,
       -4.06248972e-02,  3.48451327e-02, -1.10529416e-02,  1.46137100e-02,
       -1.78761329e-02,  1.51860285e-02, -1.81216172e-02,  1.51043646e-02,
       -7.48266591e-03, -4.99012358e-03,  4.53751964e-03,  1.59498037e-02,
        1.47847439e-02,  3.01868320e-03,  1.42118142e-03,  4.40366461e-03,
        6.27517133e-03,  3.55166686e-03,  1.28600823e-02,  6.15540636e-03,
       -2.32999689e-02, -1.42018342e-02, -2.01310937e-03,  2.20840278e-02,
       -7.77105932e-03,  1.50422241e-02,  1.11451144e-02,  1.53222446e-02,
       -9.06650253e-03,  1.15973407e-02, -1.43999238e-02,  5.93665184e-03,
       -1.82045607e-03,  6.33324595e-03, -9.28078166e-03,  5.36733912e-03,
       -2.95529051e-02,  7.21156522e-04, -3.99020050e-02,  2.45115754e-02,
        1.54059028e-02, -2.23871691e-02, -5.46136216e-03,  8.48073575e-04,
       -1.85997225e-02, -1.12029757e-02, -3.44914997e-03,  2.89814041e-02,
        4.87509415e-03,  8.89821273e-04,  2.11667089e-03,  5.99864043e-03,
       -3.41815714e-02,  1.23261161e-02, -1.48174119e-02,  2.44785214e-02,
        3.17659419e-02, -6.20703873e-03,  1.54797295e-02,  5.59890107e-03,
        3.33255032e-03,  4.63783616e-03, -6.81377774e-03,  8.01749971e-03,
        4.47022118e-03,  5.61305896e-03, -2.07519404e-02, -5.82215216e-03,
       -1.89405576e-02, -2.46076320e-02,  1.00571595e-03,  1.88542274e-02,
       -3.66329395e-02,  1.11074519e-03,  2.15371758e-02, -6.34625496e-03,
       -3.88777819e-02, -2.09388213e-02,  4.03131468e-03, -4.45295805e-02,
        4.26875117e-02, -4.94098763e-03,  3.21502654e-02, -1.49869414e-02,
        7.40492603e-03,  6.59088056e-03,  1.04319530e-03, -2.62300544e-02,
        5.28258883e-03,  2.47112201e-02,  1.72189131e-02, -1.88830991e-02,
       -1.15173423e-03,  4.01339420e-02,  4.90334452e-04, -8.22469916e-03,
        2.12907744e-02,  1.67658904e-02])

In [43]:
print(round(np.mean(ret),5))

0.00163

In [45]:
print(round(np.mean(ret),5), stats.ttest_1samp(ret,0))

0.00163 Ttest_1sampResult(statistic=1.6533388927143662, pvalue=0.09881739134445228)

The T-value is 1.65 while the P-value is 0.09. Thus, the mean is
statistically not different from zero.

## 52-week high and low trading strategy

Some investors/researchers argue that we could adopt a 52-week high and low
trading strategy by taking a long position if today's price is close to the minimum
price achieved in the past 52 weeks and taking an opposite position if today's price
is close to its 52-week high. The following Python program presents this 52-week's
range and today's position:

In [17]:
from datetime import datetime
from dateutil.relativedelta import relativedelta
ticker='ADBE'
start = datetime(2019,1,1)
end = datetime(2021,4,1)
enddate=datetime.now()
begdate=enddate-relativedelta(years=1)
df = DataReader(ticker,  'yahoo', begdate, enddate)
# x=p[-1]
# y=np.array(p.tolist())[:,-1]
# high=max(y)
# low=min(y)
# print(" Today, Price High Low, % from low ")
# print(x[0], x[-1], high, low, round((x[-1]-low)/(high-low)*100,2))

In [27]:
df

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2020-04-14,342.100006,328.470001,328.769989,340.769989,3858900,340.769989
2020-04-15,339.220001,329.649994,335.339996,332.549988,2818600,332.549988
2020-04-16,345.519989,336.040009,339.709991,342.700012,3918600,342.700012
2020-04-17,350.380005,340.500000,350.089996,344.109985,3342400,344.109985
2020-04-20,348.500000,338.750000,340.790009,344.880005,2772000,344.880005
...,...,...,...,...,...,...
2021-04-08,504.600006,498.140015,500.160004,499.839996,2026000,499.839996
2021-04-09,504.440002,492.600006,498.369995,504.040009,1886900,504.040009
2021-04-12,506.940002,498.440002,499.290009,506.029999,1584600,506.029999
2021-04-13,517.260010,506.779999,506.850006,514.859985,2195400,514.859985
2021-04-14,517.770020,509.589996,514.000000,512.732483,849293,512.732483

In [50]:
x = df["Adj Close"]

In [36]:
# x=p[-1]
# x

512.7324829101562

In [51]:
# len(x)

In [52]:
x

Date
2020-04-14    340.769989
2020-04-15    332.549988
2020-04-16    342.700012
2020-04-17    344.109985
2020-04-20    344.880005
                 ...
2021-04-08    499.839996
2021-04-09    504.040009
2021-04-12    506.029999
2021-04-13    514.859985
2021-04-14    512.732483
Name: Adj Close, Length: 253, dtype: float64

In [57]:
y=np.array(df)[:,-1]

In [58]:
y

array([340.76998901, 332.54998779, 342.70001221, 344.10998535,
       344.88000488, 328.98999023, 336.76998901, 335.36999512,
       344.1000061 , 348.5       , 333.45001221, 349.17001343,
       353.64001465, 343.83999634, 349.10998535, 356.13000488,
       362.51998901, 366.77999878, 367.51000977, 371.42001343,
       365.1000061 , 358.55999756, 355.39001465, 365.29998779,
       367.97000122, 372.20001221, 383.63000488, 382.17001343,
       385.26000977, 376.63000488, 375.17001343, 379.82998657,
       386.6000061 , 389.67999268, 390.44000244, 389.92001343,
       385.79998779, 392.8999939 , 397.77999878, 397.16000366,
       406.82000732, 387.67001343, 406.54000854, 401.33999634,
       411.67001343, 413.48999023, 420.45999146, 428.01000977,
       438.64001465, 440.54998779, 431.67999268, 436.95001221,
       426.92001343, 424.20001221, 435.30999756, 439.80999756,
       442.95001221, 452.58999634, 449.35998535, 457.67999268,
       460.83999634, 466.20001221, 442.47000122, 433.77999878,
       433.01000977, 426.29000854, 432.42001343, 455.26998901,
       444.27999878, 445.04998779, 431.73999023, 430.30999756,
       437.1000061 , 432.26000977, 436.29998779, 438.88000488,
       444.32000732, 447.97000122, 446.92001343, 449.51000977,
       464.10998535, 449.57000732, 443.29000854, 435.23001099,
       445.35998535, 450.01998901, 447.6000061 , 451.57998657,
       463.51000977, 462.01000977, 478.48001099, 473.22000122,
       476.29998779, 484.42999268, 528.48999023, 510.32000732,
       516.44000244, 513.39001465, 527.95001221, 533.79998779,
       507.79998779, 491.94000244, 462.13000488, 479.45999146,
       476.26000977, 471.3500061 , 485.91000366, 497.67001343,
       476.        , 474.29998779, 467.54998779, 475.64001465,
       486.77999878, 470.39001465, 467.67001343, 479.77999878,
       488.51000977, 489.32998657, 490.42999268, 499.51000977,
       478.98999023, 486.47000122, 478.98001099, 493.1499939 ,
       490.83999634, 502.16000366, 510.89001465, 514.30999756,
       506.30999756, 501.1499939 , 502.82000732, 495.20001221,
       494.57998657, 495.95999146, 483.6000061 , 488.5       ,
       475.20001221, 478.55999756, 456.97000122, 461.10998535,
       447.1000061 , 444.94000244, 454.01998901, 487.23001099,
       496.47000122, 494.63000488, 471.14001465, 452.        ,
       467.75      , 462.57998657, 469.33999634, 460.95001221,
       467.95001221, 459.47000122, 466.41000366, 462.92001343,
       460.60998535, 462.70001221, 470.07998657, 477.02999878,
       478.47000122, 479.1499939 , 481.26000977, 484.27999878,
       486.        , 492.25      , 495.27999878, 483.73999023,
       476.86999512, 475.91000366, 486.42001343, 482.64001465,
       489.8999939 , 495.35998535, 502.95001221, 498.39001465,
       504.17001343, 496.91000366, 499.85998535, 498.95001221,
       502.10998535, 497.45001221, 500.11999512, 485.33999634,
       485.69000244, 466.30999756, 477.73999023, 485.1000061 ,
       474.23999023, 471.6499939 , 472.04998779, 463.26998901,
       458.07998657, 456.5       , 469.73001099, 472.01998901,
       472.44000244, 473.44000244, 476.27999878, 460.        ,
       465.67001343, 458.76998901, 470.        , 484.92999268,
       481.92001343, 489.38000488, 492.11999512, 493.76000977,
       496.04998779, 492.67001343, 496.61999512, 498.83999634,
       501.64001465, 491.23001099, 488.36999512, 479.11999512,
       467.32998657, 467.79998779, 476.61999512, 459.16000366,
       459.67001343, 469.57000732, 466.58999634, 448.45001221,
       439.05999756, 440.82998657, 421.20001221, 439.17999268,
       437.01000977, 451.05999756, 444.29998779, 447.58999634,
       450.54000854, 451.01000977, 439.17999268, 441.5       ,
       452.41000366, 460.20001221, 451.51000977, 450.98999023,
       469.08999634, 469.32000732, 465.45999146, 475.36999512,
       483.33999634, 491.61999512, 491.33999634, 493.41000366,
       499.83999634, 504.04000854, 506.02999878, 514.85998535,
       512.73248291])

In [59]:
# y = p[:-1].to_list()
# y

In [60]:
high=max(y)
high

533.7999877929688

In [61]:
low = min(y)
low

328.989990234375

In [62]:
print(" Today, Price High Low, % from low ")
print(x[0], x[-1], high, low, round((x[-1]-low)/(high-low)*100,2))

 Today, Price High Low, % from low
340.7699890136719 512.7324829101562 533.7999877929688 328.989990234375 89.71

## Roll's model to estimate spread

Liquidity is defined as how quickly we can dispose of our asset without losing its
intrinsic value. Usually, we use spread to represent liquidity. However, we need
high-frequency data to estimate spread. Later in the chapter, we show how to
estimate spread directly by using high-frequency data. To measure spread indirectly
based on daily observations, Roll (1984) shows that we can estimate it based on the
serial covariance in price changes

In [63]:
from datetime import datetime
from dateutil.relativedelta import relativedelta
ticker='ADBE'
start = datetime(2019,1,1)
end = datetime(2021,4,1)
enddate=datetime.now()
begdate=enddate-relativedelta(years=1)
df = DataReader(ticker,  'yahoo', start, end)

In [64]:
df

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2019-01-02,226.169998,219.000000,219.910004,224.570007,2784100,224.570007
2019-01-03,223.630005,215.149994,220.880005,215.699997,3663500,215.699997
2019-01-04,227.649994,217.479996,219.839996,226.190002,4043400,226.190002
2019-01-07,232.600006,227.289993,229.949997,229.259995,3638500,229.259995
2019-01-08,233.770004,228.330002,232.649994,232.679993,3685900,232.679993
...,...,...,...,...,...,...
2021-03-26,469.769989,449.049988,450.250000,469.089996,3614400,469.089996
2021-03-29,472.000000,462.500000,469.029999,469.320007,3141900,469.320007
2021-03-30,469.089996,461.500000,462.579987,465.459991,2436300,465.459991
2021-03-31,482.410004,468.700012,469.700012,475.369995,3155900,475.369995
2021-04-01,487.040009,480.709991,483.119995,483.339996,2664000,483.339996

In [66]:
p=df["Adj Close"]

In [68]:
d= np.diff(p)

In [72]:
cov_= np.cov(d[:-1],d[1:])
if cov_[0,1]<0:
    print("Roll spread for ", ticker, 'is', round(2*np.sqrt(-cov_[0,1]),3))
else:
    print("Cov is positive for ",ticker, 'positive', round(cov_[0,1],3))

Roll spread for  ADBE is 8.881

Thus, during that period, Roll's spread for ADOBE is 8.881. When its value
is positive, Roll's model would fail. In a real world, it is true for many cases. Usually,
practitioners adopt two approaches: when the spread is negative, we just ignore
those cases or use other methods to estimate spread. The second approach is to add a
negative sign in front of a positive covariance.

## Amihud's model for illiquidity

According to Amihud (2002), liquidity reflects the impact of order flow on price

In [78]:
import numpy as np
import statsmodels.api as sm
from datetime import datetime
from dateutil.relativedelta import relativedelta
ticker='ADBE'
start = datetime(2020,1,1)
end = datetime(2021,1,1)
df = DataReader(ticker,  'yahoo', start, end)

In [79]:
p=np.array(df["Adj Close"])
dollar_vol=np.array(df.Volume*p)
ret=np.array((p[1:] - p[:-1])/p[1:])
illiq=np.mean(np.divide(abs(ret),dollar_vol[1:]))
print("Aminud illiq=", illiq)

Aminud illiq= 1.5447604855297214e-11

## Pastor and Stambaugh (2003) liquidity measure

In [80]:
import numpy as np
import statsmodels.api as sm
from datetime import datetime
from dateutil.relativedelta import relativedelta
ticker='ADBE'
start = datetime(2020,1,1)
end = datetime(2021,1,1)
df = DataReader(ticker,  'yahoo', start, end)

In [82]:
ret = (df["Adj Close"][1:]-df["Adj Close"][:-1])/df["Adj Close"][:-1]

Date
2020-01-02    NaN
2020-01-03    0.0
2020-01-06    0.0
2020-01-07    0.0
2020-01-08    0.0
             ...
2020-12-24    0.0
2020-12-28    0.0
2020-12-29    0.0
2020-12-30    0.0
2020-12-31    NaN
Name: Adj Close, Length: 253, dtype: float64

In [84]:
a = df["Adj Close"][1:].tolist()
b = df["Adj Close"][:-1].tolist()
c = np.subtract(a,b)
ret = np.divide(c, b)

In [85]:
ret

array([-7.83421097e-03,  5.72615024e-03, -9.58846947e-04,  1.34376564e-02,
        7.63612374e-03, -1.87990784e-03,  1.71272398e-02, -2.89326733e-03,
       -4.90381690e-03,  7.11495429e-03,  1.26237341e-02,  7.43437333e-04,
        1.71421596e-04,  4.85634525e-03, -1.10875210e-03, -1.27216361e-02,
        2.22831108e-02, -8.37492931e-03,  1.44457331e-02, -1.56976390e-02,
        1.95363247e-02,  2.44133805e-02, -3.24481233e-03,  5.22501361e-03,
       -3.72828376e-03,  1.06804439e-02, -1.94594925e-03,  1.35669676e-02,
        1.46941618e-03,  1.28855435e-02, -2.15978954e-03,  1.16932628e-02,
       -1.12711525e-02, -1.58591392e-02, -4.16678054e-02, -2.68879320e-02,
        1.01782883e-02, -3.93351382e-02,  2.25172030e-02,  4.39267613e-02,
       -3.31408973e-02,  4.45254921e-02, -3.52343194e-02, -4.06233365e-02,
       -9.19915119e-02,  8.69550855e-02, -5.15975499e-02, -9.58982645e-02,
        1.77192982e-01, -1.47451568e-01,  9.01304020e-02, -5.51618368e-02,
        4.37867861e-02, -3.95759912e-02,  4.03940977e-02,  8.88473032e-03,
       -1.31935366e-02,  5.47873870e-02, -5.21896246e-02,  4.10686611e-02,
       -4.71196982e-04, -5.35130697e-02,  9.12984323e-03, -3.40505540e-02,
        8.69180914e-02, -3.19619342e-02,  2.67050795e-02,  4.79229323e-03,
        6.11854915e-03,  6.27475300e-02, -2.41218461e-02,  3.05218006e-02,
        4.11430725e-03,  2.23771342e-03, -4.60740386e-02,  2.36481322e-02,
       -4.15712190e-03,  2.60309840e-02,  1.27869626e-02, -4.31850439e-02,
        4.71435017e-02,  1.28017901e-02, -2.77118479e-02,  1.53268644e-02,
        2.01083321e-02,  1.79428412e-02,  1.17511031e-02,  1.99032387e-03,
        1.06391760e-02, -1.70157964e-02, -1.79129237e-02, -8.84087163e-03,
        2.78847822e-02,  7.30909805e-03,  1.14955322e-02,  3.07092754e-02,
       -3.80572801e-03,  8.08539715e-03, -2.24004689e-02, -3.87646081e-03,
        1.24209638e-02,  1.78238153e-02,  7.96685598e-03,  1.95034331e-03,
       -1.33180261e-03, -1.05663354e-02,  1.84033342e-02,  1.24204758e-02,
       -1.55863824e-03,  2.43227001e-02, -4.70723995e-02,  4.86754055e-02,
       -1.27908990e-02,  2.57388179e-02,  4.42096035e-03,  1.68565174e-02,
        1.79565677e-02,  2.48358792e-02,  4.35430668e-03, -2.01339130e-02,
        1.22081626e-02, -2.29545680e-02, -6.37121975e-03,  2.61904409e-02,
        1.03374607e-02,  7.13947993e-03,  2.17631423e-02, -7.13672642e-03,
        1.85152386e-02,  6.90439546e-03,  1.16309693e-02, -5.09009231e-02,
       -1.96397551e-02, -1.77506804e-03, -1.55192745e-02,  1.43798934e-02,
        5.28420861e-02, -2.41395007e-02,  1.73311654e-03, -2.99067474e-02,
       -3.31216174e-03,  1.57793418e-02, -1.10729725e-02,  9.34617576e-03,
        5.91340170e-03,  1.23951932e-02,  8.21478627e-03, -2.34387970e-03,
        5.79521225e-03,  3.24797563e-02, -3.13287335e-02, -1.39689007e-02,
       -1.81822225e-02,  2.32749905e-02,  1.04634539e-02, -5.37750093e-03,
        8.89182398e-03,  2.64184055e-02, -3.23617607e-03,  3.56485809e-02,
       -1.09931651e-02,  6.50857226e-03,  1.70690848e-02,  9.09522495e-02,
       -3.43809405e-02,  1.19924656e-02, -5.90579308e-03,  2.83605001e-02,
        1.10805483e-02, -4.87073822e-02, -3.12327407e-02, -6.05968155e-02,
        3.75002410e-02, -6.67413704e-03, -1.03095023e-02,  3.08899912e-02,
        2.42020326e-02, -4.35429358e-02, -3.57145422e-03, -1.42314994e-02,
        1.73030201e-02,  2.34210407e-02, -3.36702087e-02, -5.78243827e-03,
        2.58942951e-02,  1.81958627e-02,  1.67852611e-03,  2.24798425e-03,
        1.85144001e-02, -4.10802970e-02,  1.56162157e-02, -1.53966128e-02,
        2.95836623e-02, -4.68416828e-03,  2.30625202e-02,  1.73849190e-02,
        6.69416667e-03, -1.55548211e-02, -1.01913920e-02,  3.33236246e-03,
       -1.51545185e-02, -1.25207112e-03,  2.79025622e-03, -2.49213355e-02,
        1.01323280e-02, -2.72261777e-02,  7.07067606e-03, -4.51145028e-02,
        9.05964094e-03, -3.03831617e-02, -4.83114210e-03,  2.04072156e-02,
        7.31466076e-02,  1.89643290e-02, -3.70615814e-03, -4.74900229e-02,
       -4.06248972e-02,  3.48451327e-02, -1.10529416e-02,  1.46137100e-02,
       -1.78761329e-02,  1.51860285e-02, -1.81216172e-02,  1.51043646e-02,
       -7.48266591e-03, -4.99012358e-03,  4.53751964e-03,  1.59498037e-02,
        1.47847439e-02,  3.01868320e-03,  1.42118142e-03,  4.40366461e-03,
        6.27517133e-03,  3.55166686e-03,  1.28600823e-02,  6.15540636e-03,
       -2.32999689e-02, -1.42018342e-02, -2.01310937e-03,  2.20840278e-02,
       -7.77105932e-03,  1.50422241e-02,  1.11451144e-02,  1.53222446e-02,
       -9.06650253e-03,  1.15973407e-02, -1.43999238e-02,  5.93665184e-03,
       -1.82045607e-03,  6.33324595e-03, -9.28078166e-03,  5.36733912e-03])

In [86]:
dollar_vol=np.array(df["Adj Close"][1:])*np.array(df.Volume[1:])

In [91]:
date=[]
d0=df.index

In [95]:
for i in range(0,len(ret)):
    date.append(''.join([d0[i].strftime("%Y"),d0[i].strftime("%m"),d0[i].strftime("%d")]))

In [97]:
tt=pd.DataFrame(ret,np.array(date,dtype="int64"),columns=['ret'])

In [98]:
tt2=pd.DataFrame(dollar_vol,np.array(date,dtype="int64"),columns=['dollar_vol'])

In [109]:
ff = factors = pd.read_csv("fama-french.csv", skiprows=3, index_col = 0)

In [110]:
ff

          Mkt-RF   SMB   HML   RMW   CMA     RF
19630701   -0.67  0.00 -0.34 -0.01  0.15  0.012
19630702    0.79 -0.27  0.27 -0.07 -0.19  0.012
19630703    0.63 -0.17 -0.10  0.17 -0.33  0.012
19630705    0.40  0.08 -0.27  0.08 -0.33  0.012
19630708   -0.63  0.04 -0.19 -0.29  0.13  0.012
...          ...   ...   ...   ...   ...    ...
20210222   -1.12  0.68  3.14  1.66  0.90  0.000
20210223   -0.15 -1.05  0.90  1.08 -0.19  0.000
20210224    1.15  1.48  1.34 -0.29  0.32  0.000
20210225   -2.73 -0.90  0.87  1.00  0.47  0.000
20210226   -0.28  0.38 -1.56 -0.06 -0.38  0.000

[14514 rows x 6 columns]

In [105]:
ff = ff.set_index(ff.iloc[:, 0])

In [106]:
ff

            Unnamed: 0  Mkt-RF   SMB   HML   RMW   CMA     RF
Unnamed: 0
19630701      19630701   -0.67  0.00 -0.34 -0.01  0.15  0.012
19630702      19630702    0.79 -0.27  0.27 -0.07 -0.19  0.012
19630703      19630703    0.63 -0.17 -0.10  0.17 -0.33  0.012
19630705      19630705    0.40  0.08 -0.27  0.08 -0.33  0.012
19630708      19630708   -0.63  0.04 -0.19 -0.29  0.13  0.012
...                ...     ...   ...   ...   ...   ...    ...
20210222      20210222   -1.12  0.68  3.14  1.66  0.90  0.000
20210223      20210223   -0.15 -1.05  0.90  1.08 -0.19  0.000
20210224      20210224    1.15  1.48  1.34 -0.29  0.32  0.000
20210225      20210225   -2.73 -0.90  0.87  1.00  0.47  0.000
20210226      20210226   -0.28  0.38 -1.56 -0.06 -0.38  0.000

[14514 rows x 7 columns]

In [111]:
ff.to_pickle("c:/temp/ffMonthly.pickle")

In [113]:
tt3 = pd.merge(tt,tt2,left_index=True,right_index=True)

In [114]:
final=pd.merge(tt3,ff,left_index=True,right_index=True)

In [116]:
final

               ret    dollar_vol  Mkt-RF   SMB   HML   RMW   CMA     RF
20200102 -0.007834  5.234635e+08    0.86 -0.95 -0.36  0.20 -0.22  0.006
20200103  0.005726  6.256061e+08   -0.67  0.28  0.02 -0.18 -0.15  0.006
20200106 -0.000959  8.337417e+08    0.36 -0.22 -0.56 -0.19 -0.32  0.006
20200107  0.013438  7.597007e+08   -0.19 -0.04 -0.21 -0.11 -0.31  0.006
20200108  0.007636  5.536739e+08    0.47 -0.17 -0.63 -0.17 -0.12  0.006
...            ...           ...     ...   ...   ...   ...   ...    ...
20201223  0.005937  2.945175e+08    0.10  0.83  2.00  0.27  0.43  0.000
20201224 -0.001820  7.561088e+08    0.21 -0.43 -0.17  0.24 -0.05  0.000
20201228  0.006333  7.200759e+08    0.46 -0.65  0.32  1.46  0.50  0.000
20201229 -0.009281  7.610488e+08   -0.40 -1.42  0.24  0.75 -0.28  0.000
20201230  0.005367  7.312254e+08    0.27  1.03  0.04 -0.67 -0.06  0.000

[252 rows x 8 columns]

In [117]:
y=final.ret[1:]-final.RF[1:]

In [120]:
x1=final["Mkt-RF"][:-1]

In [123]:
x2=np.sign(np.array(final.ret[:-1]-final.RF[:-1]))*np.array(final.dollar_vol[:-1])

In [124]:
x3=[x1,x2]

In [126]:
n= np.size(x3)

In [136]:
x=np.reshape(x3,(int(n/2),2))

In [137]:
x=sm.add_constant(x)

In [138]:
results=sm.OLS(y,x).fit()

In [139]:
print(results.params)

const    7.684751e-04
x1      -1.542627e-12
x2      -8.114868e-13
dtype: float64